### ISSUE TITLE
[Feature Request] Want archived file as source

### ISSUE THREAD

**Issue by hcoona** [google/copybara#100]
Sometimes libraries are provided within an archived file. I'd like to copy the content into our repository and maintain the relationship with the help of copybara.

**Comment by mikelalcon** [comment]
You mean like a jar file? Any specific example? We've been thinking for a
while to have a maven.origin like node.

**Comment by mikelalcon** [comment]
Hi Shuai,

Closing this for now, but let us know if you still need this.
