### ISSUE TITLE
Unable to migrate a new github repo

### ISSUE THREAD

**Issue by jawsthegame** [google/copybara#106]
I am trying to migrate an existing local git repo to a fresh github repo and I am getting the following error:

`ERROR: Previous revision label GitOrigin-RevId could not be found in GitDestination{repoUrl=https://github.com/jawsthegame/myrepo.git, fetch=master, push=master} and --last-rev or --init-history flags were not passed`

Adding those flags doesn't change the result, and I am using --force.

I have also tried initializing the github repo with a README, still no luck.

Has anyone else seen this issue?

**Comment by jawsthegame** [comment]
This was a silly arguments ordering issue.

**Comment by remod** [comment]
I am getting the same behavior with the example. It seems like all command line arguments are ignored. May I ask how you resolved this?

**Comment by mikelalcon** [comment]
@remod We don't have much experience using Docker (the config was an external contribution). What is the CLI you are using?

**Comment by remod** [comment]
@mikelalcon Thanks for the response. I managed to get the example to run with

1. Create a file `copy.bara.sky` with the content from the [example](https://github.com/google/copybara).
1. Run
   ```
   (mkdir /tmp/foo ; cd /tmp/foo ; git init --bare)
   ```
1. Run 
   ```
   docker run -v /tmp:/tmp -v ~/.ssh:/root/.ssh -v ~/.gitconfig:/root/.gitconfig -v "$(pwd)":/usr/src/app -e COPYBARA_CONFIG='copy.bara.sky --force' -it copybara copybara
   ```

(I originally thought `--force` can just be appended to `copybara`)
