### ISSUE TITLE
getInfo returns changes `getAvailableToMigrate` for the ones which already migrated

### ISSUE THREAD

**Issue by pavelmigolinets** [google/copybara#108]
Hi, 

we are using copybara as embedded one. 
our use case next: 
1. we are using [.getInfo](https://github.com/google/copybara/blob/master/java/com/google/copybara/InfoCmd.java#L159) for getting list of changes that available for migration
2. if there are some changes -> notify user about it
3. user triggering migration process
4. our service creating branch 
5. migrating code to this branch
6. opening PR 
7. merge with rebase if passing checks

problem that .getInfo provides list of changes available to migrate even when they already migrated.  we are using `lastRevision` as starting point, but no updating it after migration. 
I know that we are doing something wrong which not allowed to get info correctly. 

migration for this case throwing expected exception `Iterative workflow produced no changes in the destination for resolved ref: ` 

I know that it's not trivial use case of copybara, but I would really appreciate if you will advice something. 

Thanks!!! 

Cheers,
Pavel

**Comment by mikelalcon** [comment]
HI Pavel,

IIUC what you are saying is that info says there are changes but then the migration produces no changes. Do you use the same config for info and migration? Same destination url and branch?

**Comment by pavelmigolinets** [comment]
Hi Mikel, 
I'm sorry for the long time with no response.

yes, I'm using same config for both. I'm using build of copybara from - 20.11.2019. It's working fine for regular(CMD) use case, but for programmatic way I'm getting list of changes available for migration. 

Exception type for the migration is `EmptyChangeException` which came from the condition `if (migratedChanges == 0)` -> WorkflowMode.java:218

**Comment by mikelalcon** [comment]
Hi Pavel,

Sorry for the late response. I cannot thing of a reason for this to happen. info CMD and getInfo() should return the same stuff as they are calling the same code. Since I don't have the config and you already do some development with Copybara as a library, would you mind debugging both and see where is the difference?

info CMD calls getInfo at: java/com/google/copybara/InfoCmd.java line 159

**Comment by pavelmigolinets** [comment]
Hi Mikel, 

sorry for the long time no response. I checked everything again, and it was my bad from the beginning with no providing `last-rev` param to info command.

Both CMD and Programmatic way respecting `last-rev` param and showing the changes list according to the value provided. I'm trully sorry for waisting  your time on this. 

Thanks for the help!

**Comment by mikelalcon** [comment]
Great to hear! Let us know if you find any other issue. 

Cheers,
Mikel.
