### ISSUE TITLE
name 'maven_jar' is not defined

### ISSUE THREAD

**Issue by Lefttyre** [google/copybara#109]
follow ReadMe.md, I get following errors

(base) PengdongdeMacBook-Pro:copybara pengdongzhu$ bazel build //java/com/google/copybara
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:21:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:27:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:34:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:41:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:48:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:55:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:62:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:69:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:76:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:84:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:92:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:100:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:107:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:114:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:121:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:128:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:137:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:144:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:151:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:158:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:165:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:172:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:179:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:236:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:21:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:27:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:34:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:41:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:48:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:55:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:62:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:69:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:76:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:84:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:92:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:100:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:107:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:114:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:121:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:128:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:137:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:144:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:151:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:158:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:165:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:172:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:179:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:236:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:21:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:27:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:34:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:41:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:48:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:55:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:62:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:69:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:76:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:84:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:92:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:100:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:107:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:114:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:121:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:128:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:137:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:144:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:151:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:158:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:165:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:172:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:179:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:236:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:21:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:27:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:34:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:41:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:48:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:55:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:62:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:69:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:76:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:84:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:92:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:100:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:107:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:114:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:121:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:128:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:137:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:144:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:151:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:158:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:165:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:172:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:179:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:236:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:21:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:27:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:34:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:41:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:48:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:55:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:62:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:69:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:76:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:84:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:92:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:100:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:107:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:114:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:121:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:128:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:137:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:144:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:151:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:158:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:165:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:172:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:179:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:236:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:21:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:27:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:34:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:41:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:48:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:55:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:62:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:69:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:76:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:84:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:92:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:100:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:107:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:114:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:121:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:128:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:137:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:144:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:151:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:158:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:165:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:172:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:179:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:236:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:21:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:27:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:34:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:41:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:48:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:55:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:62:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:69:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:76:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:84:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:92:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:100:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:107:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:114:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:121:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:128:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:137:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:144:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:151:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:158:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:165:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:172:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:179:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:236:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:21:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:27:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:34:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:41:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:48:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:55:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:62:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:69:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:76:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:84:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:92:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:100:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:107:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:114:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:121:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:128:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:137:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:144:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:151:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:158:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:165:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:172:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:179:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:236:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:21:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:27:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:34:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:41:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:48:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:55:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:62:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:69:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:76:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:84:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:92:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:100:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:107:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:114:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:121:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:128:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:137:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:144:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:151:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:158:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:165:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:172:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:179:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:236:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:21:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:27:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:34:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:41:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:48:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:55:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:62:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:69:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:76:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:84:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:92:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:100:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:107:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:114:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:121:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:128:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:137:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:144:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:151:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:158:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:165:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:172:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:179:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:236:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:21:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:27:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:34:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:41:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:48:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:55:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:62:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:69:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:76:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:84:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:92:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:100:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:107:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:114:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:121:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:128:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:137:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:144:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:151:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:158:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:165:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:172:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:179:1: name 'maven_jar' is not defined
ERROR: /Users/pengdongzhu/workspace/copybara/WORKSPACE:236:1: name 'maven_jar' is not defined
ERROR: error loading package 'external': Package 'external' contains errors
INFO: Elapsed time: 0.081s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by Lefttyre** [comment]
revert bazel to 1.2.1 is OK, 2.0.0 has this issue

**Comment by mikelalcon** [comment]
Yes, we need to migrate from maven_jar.

**Comment by natansil** [comment]
Hi, any ETA on migration from maven_jar?

**Comment by mikelalcon** [comment]
Hi! ae9fecb4742f2f4b3cdcea6ce9fcf9d72789d29f should have fixed this.

**Comment by natansil** [comment]
Thanks!

**Comment by mcmillen** [comment]
Confirming that ae9fecb appears to have fixed build & test with Bazel 2 for me.
