### ISSUE TITLE
Customize git binary path

### ISSUE THREAD

**Issue by ittaiz** [google/copybara#11]
We need to customize the git binary path since we want to actually use a wrapper that:
exports some environment properties for Copybara to leverage (username, email, etc).

We tried setting `GIT_EXEC_PATH` in the env but that confuses git since we can't have wrapper sit in the actual `GIT_EXEC_PATH`.

I experimented in my repo in changing `GitRepository#resolveGitBinary` to try and first read `GIT_BINARY_PATH` from the environment and if not fallback to `GIT_EXEC_PATH` and then back to `git` (like it does today).

That solved my problem.

I'd be really happy to send a PR for this. WDYT?

**Comment by mikelalcon** [comment]
That doesn't work when you have git extensions (We tried that :)). 

Why cannot you use your custom environment like:

```
      GeneralOptions generalOptions = generalOptionsArgs.init(environment, fs, console);
      allOptions.add(generalOptions);
      Options options = new Options(allOptions);
```

You can also use --git-committer-name and --git-committer-email flags, so I suspect you don't need a wrapper git for that.

**Comment by ittaiz** [comment]
I don't understand what you're doing in the first part, I think that's what we're doing. Why should that help?
With respect to the second part using the above flags sounds good. The third env variable we're setting is GIT_SSH_COMMAND so that we can bypass the 2fa problem with github.
Can we leverage `core.sshCommand` from git (2.10+)? Not that much of a git expert but can we pass that like we pass the other flags?

**Comment by mikelalcon** [comment]
The environment that we pass here:

generalOptionsArgs.init(**environment**,...)

Is the one that we pass to any subcommand that we invoke (Like git). So you can set GIT_SSH_COMMAND in that map and it will be passed as environment to git.

Another thing you can do is use http://github.com instead of ssh://..|git:// and use .netrc to store user and a generated token as password (that works for 2fa)

**Comment by ittaiz** [comment]
I didn't know that the environment is passed on to subcommand, cool! I'll
give it a try. This might indeed render my script as unneeded.

**Comment by mikelalcon** [comment]
K, let me know if it works :)

**Comment by ittaiz** [comment]
Indeed passing GIT_SSH_COMMAND to the env, works. Thanks!
