### ISSUE TITLE
Cannot build docker image

### ISSUE THREAD

**Issue by shouichi** [google/copybara#110]
Steps to reproduce

```
cd ~/path/to/copybara
docker build -t copybara .
```

c7e31c66a979300daedbc9bb266787013486746e is fine but after that it fails.

**Comment by mikelalcon** [comment]
What is the error you are getting? The error is in https://github.com/google/copybara/commit/61dff6bbc9dd5b4197f198c4e04fa44d47e690fc, that updates bazel. Chances are that you need a newer bazel version in the docker image.

**Comment by shouichi** [comment]
> What is the error you are getting?

```
ERROR: /usr/src/copybara/WORKSPACE:21:1: name 'maven_jar' is not defined
```

https://github.com/anipos/copybara-docker-image/runs/361734233

> Chances are that you need a newer bazel version in the docker image.

The Dockerfile uses the `latest` tag and the build is not reproducible 😢 

https://github.com/google/copybara/blob/297495401be92e45d590c377859141785151ab50/Dockerfile#L15

**Comment by mikelalcon** [comment]
Seems we need to migrate our maven_jar rules. Based on https://github.com/google/copybara/issues/109 reverting temporarily the docker image to 1.2.1 should fix it.

(Closing this one in favor of #109 )

**Comment by shouichi** [comment]
Thanks!
