### ISSUE TITLE
Use reposurgeon to preserve commit messages

### ISSUE THREAD

**Issue by abitrolly** [google/copybara#113]
https://github.com/google/mediapipe/commits/master imports by copybara have no commit messages. Maybe use https://gitlab.com/esr/reposurgeon instead of reinventing the wheel?

**Comment by mikelalcon** [comment]
Copybara is very flexible preserving the message. It is up to their users how they transform the message. Closing as this is not a feature request (Feel free to open one for mediapipe project).

**Comment by abitrolly** [comment]
https://github.com/google/mediapipe/issues/369
