### ISSUE TITLE
Run Copybara in GitHub actions?

### ISSUE THREAD

**Issue by wilmol** [google/copybara#123]
Hi, is it possible to run Copybara in GitHub actions?

Thinking someone could create an action that wraps it, or would it be easier to use Docker?

**Comment by mikelalcon** [comment]
As far as I know nobody has tried, but it would be cool :)

**Comment by wilmol** [comment]
I got it working here: https://github.com/wilmol/copybara-action

**Comment by rockwotj** [comment]
I've got an example of using a GitHub action [here](https://github.com/oilpan-gc/cppgc/blob/main/.github/workflows/update.yml). It also uses the github actions user so there is no need to setup personal access tokens or SSH keys like https://github.com/will-molloy/copybara-action
