### ISSUE TITLE
 How to reference environment variables in copy.bara.sky

### ISSUE THREAD

**Issue by jigt-gft** [google/copybara#125]
Hi!
The idea is to use environment variables in the copy.bara.sky configuration file.
For example:
```
$> echo $MIGRATION_MODE
SQUASH
```
```
core.workflow(
    name = "import",
    mode = ${MIGRATION_MODE},

    origin = git.github_origin(
      url = sot_url,
      ref = "master",
    ),
```
Thanks in advance!

**Comment by sudoforge** [comment]
Can I ask what your use case for this is? It would appear that you want to change the mode for the migration; assuming that you're only going to alternate between `ITERATIVE` and `SQUASH`, I think a cleaner way to accomplish this might be to set the default `mode = ITERATIVE` and then use the `--squash` command line flag to override this when necessary.

**Comment by yang** [comment]
@sudoforge Is there any other more general way to parameterize the builds?

For instance, if we want to apply a workflow to a variable destination repo path (which can vary across dev environments).

**Comment by mikelalcon** [comment]
I would create a workflow per environment (With starlark is easy)

**Comment by sudoforge** [comment]
> @sudoforge Is there any other more general way to parameterize the builds?

if i'm understanding what you're getting at, you might want to explore building a macro for your parameterized workflow.
