### ISSUE TITLE
Docker: ERROR: Copybara config file filename should be 'copy.bara.sky' but it is 'something.else.sky'

### ISSUE THREAD

**Issue by fuxingloh** [google/copybara#127]
In README.md
> A few environment variables exist to allow you to change how you run copybara:
> * COPYBARA_CONFIG=copy.bara.sky
> allows you to specify a path to a config file, defaults to root copy.bara.sky

I tried running it:

```bash
docker run \
       -e COPYBARA_CONFIG='something.else.sky' \
       -e COPYBARA_WORKFLOW='master' \
       -v "$(pwd)":/usr/src/app \
       -it copybara copybara
```

However, when I specific a config other than `copy.bara.sky` the error; **"Copybara config file filename should be 'copy.bara.sky' but it is 'something.else.sky'"** will be raised.

**Comment by mikelalcon** [comment]
This is expected. Copybara requires that the main config file is called "copy.bara.sky". The path can change, but not the name.
