### ISSUE TITLE
How to remove the GitOrigin-RevId label

### ISSUE THREAD

**Issue by mikeshawdev** [google/copybara#128]
Hi,

I was wondering how the GitOrigin-RevId label can be removed. I've tried using metadata.remove_label in the transformations, but it doesn't remove it.

Sorry if this isn't the appropriate place for this question. I tried posting in the google groups forum, but it wouldn't let me due to permissions

Cheers,

Mike

**Comment by hsudhof** [comment]
Hi Mike,

The origin label is copybara's bookmark to know where it left off and to line up changes in the repos. Fundamentally, there are ways to handle this by extending the classes to have implementations that read this data from another source.

**Comment by mikeshawdev** [comment]
Hi @hsudhof,

Cheers for getting back to me on this so quickly 👍 In that case, I'll leave them in. Not worth removing them as they're being used for core functionality

Mike
