### ISSUE TITLE
** does not include files in the current directory

### ISSUE THREAD

**Issue by michaeleisel** [google/copybara#130]
It would be great if its behavior matched that of Bazel build files, or if not, it was prominently documented as such.

**Comment by hsudhof** [comment]
Hi,

do you have a minimal example where a glob does not match a file you would have expected it to match?

Cheers,
~H

**Comment by mikelalcon** [comment]
Yes. Copybara Globs are the standard unix/java globs. We document it here:

https://github.com/google/copybara/blob/master/docs/reference.md#all-build-files-recursively

**Comment by michaeleisel** [comment]
Coming from Bazel, `**` matches in the current directory, e.g.:
```
cc_library(
        name = "Yo",
        srcs = glob(["**/*.c"]), # Matches a.c, source/a.c, etc.
)
```

But, it sounds like there are multiple common ways of doing globs
