### ISSUE TITLE
Bazel Test seems to be failing on master

### ISSUE THREAD

**Issue by SecurityInsanity** [google/copybara#132]
As of ~4 days ago running: `bazel test //...` on master has started failing. This can be seen on a GitHub action CI where I build nightly copybara images: [This is the first test failure, although all 4 days since have been solid of this test failing](https://github.com/SecurityInsanity/openjdk-panama-vector-docker/runs/956196460?check_suite_focus=true).

This has been tested on two linux setups, one running bazel 3.4.1, and the CI actions uses bazel 3.3.0. A failed output log from the test that is failing is: [HERE](https://gist.github.com/SecurityInsanity/76d9a8bdb16364b920123d1961b33182).

Please let me know any other information you need, Thanks!

**Comment by hsudhof** [comment]
Hi,

I cannot reproduce this, do you happen to have the details of the GithubPrOriginTest failure? Might be the git version used.

**Comment by SecurityInsanity** [comment]
Hey @hsudhof I've attached the log above in the issue of the failing test. The version of git on the host that produced that log is:

```
git --version
git version 2.28.0
```
