### ISSUE TITLE
Any way to force push?

### ISSUE THREAD

**Issue by politician** [google/copybara#136]
I would like to protect the branch in the destination (GitHub) repo to make sure that a developer would receive at least a warning if he's pushing/merging into it.

One way to overcome the branch protection is to use `git push --force` (if enabled). How could I ensure that my Copybara workflow is always force pushing?

As an additional benefit, force-pushing would ensure that histories between two repos are always in sync as they're supposed to be.

Any objections to this kind of workflow?

**Comment by mikelalcon** [comment]
`--git-destination-non-fast-forward` should do the tick.
