### ISSUE TITLE
[Feature request] Give attribution to all the authors in case of multiple commits

### ISSUE THREAD

**Issue by scriptnull** [google/copybara#141]
when copybara is used in `CHANGE_REQUEST` mode, I think it does a squash of all the commits in the origin and pushes that squashed commit to the destination. (this based on my observation - correct me if I am wrong)

When there are multiple commits in the origin from a single author, this is fine. But when there are multiple commits in the origin from different authors, then copybara makes the author of the latest commit to be the author of the squashed commit. Instead, we should try to preserve the authors of all the commits.

It seems like git does not have native support for adding multiple authors to a single commit. Instead most git clients support the `Co-authored-by` trailer in commit messages in-order to denote that multiple authors have contributed to a single commit. ( [reference](https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors) )

So, it would be better if copybara automatically adds `Co-authored-by` when squashing multiple commits from different authors  while operating in `CHANGE_REQUEST` / `SQUASH` mode.

**Comment by scriptnull** [comment]
I have a working draft of this feature for `CHANGE_REQUEST` mode. We could easily make it work for `SQUASH` mode too.

Please let me know if it ok to have this feature in the upstream.

**Comment by hsudhof** [comment]
Hi,

Thank you for using copybara and your offer to contribute, we invite and accept contributions and are glad to discuss them.

In this particular case, I wonder whether this is something that should be tied to the workflow mode, it seems to me that this should be well within the scope of a starlark transformation.

I.e. something along the lines of
```
def add_authors(ctx):
    for change in ctx.changes.current:
      ctx.add_label("Co-authored-by", change.author.email, ":")
```

What do you think?

Cheers,
~H

**Comment by scriptnull** [comment]
@hsudhof That is really cool - the way you could think of solutions in terms of starlark!

I was trying to achieve this in a hacky way by [modifying the Java code](https://github.com/scriptnull/copybara/commit/401fc5abfc97a8cd9e1135ec7fb061a304c8773d) and kind of [worked around it for now](https://github.com/scriptnull/copybara/commit/f189a2f62298f3eb4131e6329c5ae8bddb127d64).

**Comment by hsudhof** [comment]
This is of course a very basic version, for a real implementation one would add de-duping etc. 

At some point, I hope to be able to add more scripting examples to the documentation and maybe a standard library.
