### ISSUE TITLE
Reopen closed ticket on PR rollback

### ISSUE THREAD

**Issue by bhack** [google/copybara#155]
We need to reopen the connected ticket on PR rollback.

Check:
https://github.com/tensorflow/tensorflow/issues/43038
https://github.com/tensorflow/tensorflow/pull/43040#issuecomment-751847714

**Comment by hsudhof** [comment]
The biggest issue is that GitHub's PR state model has "merged" as a final state.

**Comment by bhack** [comment]
The PR yes but we could reopen the connected ticket and notify the PR with a comment.

**Comment by bhack** [comment]
Yes honestly I don't know the boundaries between copybara  API and a copybara operational bot  cause I am not internal.

**Comment by hsudhof** [comment]
This should be in the scope of a copybara after migration hook, https://github.com/google/copybara/blob/master/docs/reference.md#github_api_obj

**Comment by bhack** [comment]
I let to @mihaimaruseac and @nikitamaia to comment on this as I don't have any visibility on the TF copybara bot/service.

**Comment by bhack** [comment]
@mihaimaruseac Can we close this or do we need something else from copybara?
