### ISSUE TITLE
copybara: strip_begin and end meaning?

### ISSUE THREAD

**Issue by lcskrishna** [google/copybara#157]
Hello,
I'm wondering what does the copybara:strip_begin and copybara: strip_end mean? 
Where can i look for the documentation ?

**Comment by hsudhof** [comment]
Hi,

Not sure where you ran into this, but it's not something with any semantics in copybara itself. Users have build libraries to remove code blocks in transforms, this is probably one of them.

Cheers,
~H

**Comment by lcskrishna** [comment]
Thanks, understood !!
