### ISSUE TITLE
Would be good to refactor NonReversibleValidationException into exception package

### ISSUE THREAD

**Issue by ignite1771** [google/copybara#159]
## Expected Behavior
All exception classes are categorized into the exception package.

## Current Behavior
https://github.com/google/copybara/blob/abec1ba62c1fc00c142633708c93b65dd402a8ce/java/com/google/copybara/NonReversibleValidationException.java#L17-L36

There is a TODO in the comment of the file implies that this class should be also categorized into exception package.

## Possible solution
I would like to send a PR to this, for refactoring the class and solving the affected bazel build dependency configuration.
By doing so, the source code would have better modularity.
<br/>
Any pointers would be greatly appreciated.
Thanks!

**Comment by mikelalcon** [comment]
Sure, that would be great. My bet is that I didn't do it because there was a circular dependency, so it might be a bit tricky.

**Comment by ignite1771** [comment]
Got it. I will try to work on it.

**Comment by sheltshamu** [comment]
what's the update on this issues?

**Comment by ignite1771** [comment]
@sheltshamu Already merged in commit https://github.com/google/copybara/commit/d05231149ac95582f8b6db44c9b4d41ffbb6abdc so will be closed.
