### ISSUE TITLE
Add new files

### ISSUE THREAD

**Issue by nicolasmanic** [google/copybara#170]
Is it possible before pushing to the destination to add new files. From the docs it seems that it's possible only to modify existing files not create new ones.

**Comment by hsudhof** [comment]
Yes, you can create synthetic files during a workflow using the ctx object:
https://github.com/google/copybara/blob/master/docs/reference.md#transformwork

You can add starlark functions (or lambdas) taking a single param as a transform to access this.

**Comment by nicolasmanic** [comment]
Ok it seems I missed some things from the doc sorry.
So if I understand correctly by the [doc](https://github.com/google/copybara/blob/90a895858882999759b8dd0008b7a167f1bb0b94/docs/reference.md#destination_readercopy_destination_files) we can add all the files of `path/to/ from` to workdir of copybara and then use [core.move](https://github.com/google/copybara/blob/90a895858882999759b8dd0008b7a167f1bb0b94/docs/reference.md#coremove) to move the files to the correct position within the transferred repo.

**Comment by hsudhof** [comment]
oh, yes, exactly :)

**Comment by nicolasmanic** [comment]
hmm it seems that I'm not able to do what I want and I'm not sure why, I have the following:
```python
def add_external_files(ctx):
    file_1 = ctx.read_path(path = '/tmp/config/file_1.txt')
    file_2 = ctx.read_path(path = '/tmp//config/file_2.txt')
    ctx.write_path(ctx.new_path("src/file_1.txt"), file_1)
    ctx.write_path(ctx.new_path("src/file_2.txt"), file_2)
```

So I have 2 external to the copybara workdir files (`/tmp/config/file_1.txt`, `/tmp//config/file_2.txt`) that I want to include before pushing to destination (under `src/` folder), but it fails with:
> Error in read_path: read_path() got named argument for positional-only parameter 'path'

Any idea how to resolve it?

**Comment by hsudhof** [comment]
For a simple copy, look at https://github.com/google/copybara/blob/master/docs/reference.md#corecopy

Otherwise, the issue is that read_path takes a positional arg, not a named - i.e., drop the "path =".

**Comment by nicolasmanic** [comment]
Thanks for the quick reply so I have tried dropping the "path =" but it fails cause the input must be Path and I provide string.

As for the `core.copy` sadly it doesn't work it only takes relative paths and since my files are outside of copybara workdir I have no way of referencing them.
The actual error message is:
> Error in copy: '/tmp/config/file_1.txt' is not a valid path: path must be relative, but it starts with /: /tmp/config/file_1.txt

**Comment by hsudhof** [comment]
Copybara will not allow files outside the workdir, as this would break the self-containedness of the process. The inputs are the  origin_files (copied to the workdir), the config files (including patch files) and - somewhat of an escape - reading from the destination via a destination_reader.

You need to call ctx.new_path  (primaryBranchMigration) to obtain a path object. Note that you can delete files from the workdir, so adding inputs to the origin_files might work?

**Comment by nicolasmanic** [comment]
So my case is that I fetch from a remote (origin) and push to a different remote (destination). At the host that runs copybara, I have a couple of files (licences, metadata etc.) that are not present to origin but should be included in the destination. What would be the right way of handling those cases?

**Comment by hsudhof** [comment]
Depends, in that case we would probably have another workflow handing the files with another SoT (your local repo).

**Comment by mikelalcon** [comment]
If the files are relatively static you can embed it in the config file.

content = """
License
that we want to copy
"""

ctx.write(path, content)

**Comment by nicolasmanic** [comment]
yes they are relatively static, I will go with that it seems possible one last question 
with `ctx.write(path, content)` you mean `ctx. write_path(path, content)`

**Comment by mikelalcon** [comment]
yeah, sorry, I wasn't on the computer :)
