### ISSUE TITLE
Adding a header to all files

### ISSUE THREAD

**Issue by menny** [google/copybara#171]
We would like to add a header to all the files that are moved between the source repo and the target.
Use-cases:
1) adding a license header
2) adding a notice header about the source of the files
3) etc.

Is something like that possible? Right now, the only solution I have is to run a script after the copybara run and append the header to the files.

**Comment by hsudhof** [comment]
This is a fairly common use-case for the core.replace transformation - you can match the beginning of the file or a standard string in your files to add a license header.

**Comment by menny** [comment]
oh.. that's actually pretty clever. Thank you.

**Comment by menny** [comment]
I ended up with adding `core.replace` to the `transformation` list:
```
core.replace(
            before = "${code}",
            after = "/*NOTICE TO ADD AS HEADER*/\n${code}",
            multiline = True,
            paths = glob([
                "**/*.java",
                "**/*.kt",
            ]),
            first_only = True,
            regex_groups = {
                "code": ".*",
            },
        ),
```
