### ISSUE TITLE
Migrate initial repo into empy repo: ERROR: Unknown option: --git-first-commit

### ISSUE THREAD

**Issue by DarthHater** [google/copybara#18]
Hello again!

I'm trying to run Copybara like so: `copybara copy.bara.sky --git-first-commit`

I get:

```
Copybara source mover (Version: Unknown version)
ERROR: Unknown option: --git-first-commit

ERROR: Try 'copybara --help'.
```

I'm following the instructions in pretty much verbatim minus some tiny differences: https://github.com/google/copybara/blob/master/docs/examples.md#basic-git-to-git-import

My local differences are:
- using SSH over https for git repo
- using one of @sonatype 's internal repos to test this on versus Copybara

I don't think either have any impact here, as I think this is just an old command flag that no longer exists? I'd be curious what the steps are now to get copybara working on pushing an existing repo to a new bare one.

**Comment by mikelalcon** [comment]
Good catch. Use --force instead. I'll update the documentation.

**Comment by mikelalcon** [comment]
If you are using ITERATIVE mode you'll probably also need to use --last-rev
