### ISSUE TITLE
Requires write permissions

### ISSUE THREAD

**Issue by Hixie** [google/copybara#180]
It would be nice if (when Copybara is used to copy _out_ of a repo) it could be configured with only read access.

**Comment by hsudhof** [comment]
Copybara should not require write access to copy something out, where does it say otherwise?

**Comment by Hixie** [comment]
![2021-07-16-113238_967x448_scrot](https://user-images.githubusercontent.com/551196/125993337-06892f07-fd04-4b41-b073-3ebbab02e451.png)

**Comment by hsudhof** [comment]
This seems to be a google specific question to which there are google specific answers :)
