### ISSUE TITLE
Is it possible to use http instead of https in git?

### ISSUE THREAD

**Issue by tkyggit** [google/copybara#183]
Hi all

Even if I specify http as origin and destination, it forces me to use https with the following message

is not valid - should be using https.

**Comment by mikelalcon** [comment]
We do it on purpose, for security reasons. I recommend you to use https, but if not possible, you could use a local fork that disables this check:

https://github.com/google/copybara/blob/797188c119975441b71c0fd84dce0b2bf4a67a28/java/com/google/copybara/util/RepositoryUtil.java#L31
