### ISSUE TITLE
Is Copybara stateless?

### ISSUE THREAD

**Issue by hderms** [google/copybara#196]
More specifically, is all copybara state defined (in the example of git-to-git copy from A to B) by the state of the repositories A and B? i.e. Copybara is not dependent on any local filesystem state in order to determine the appropriate operations to perform.

Example:
```
# first run
copybara copy.bara.sky  --last-rev=foobar

#subsequent runs
copybara copy.bara.sky
```

When Copybara is in `ITERATIVE` mode, one would desire that Copybara would be idempotent when running `copybara copy.bara.sky` if there were no new changes from source repository A, and that it could determine this solely from the repositories A and B.

I believe this to be the case based on experimenting with Copybara on my local machine, but I don't have explicit evidence of this, and the binary appears to use `~/copybara` as a folder to store local state (such as caches), as evidenced by the Docker example: `docker run -it -v "$(pwd)":/usr/src/app copybara copybara`.

If what I've suggested is indeed the case, it might be worth mentioning this in the README, or other documentation, as I'm sure it has the potential to assuage concerns of potential users, and thereby drive more usage of the library.

**Comment by mikelalcon** [comment]
Thanks for noticing it! Yes, it is stateless. We designed like that on purpose.

Makes sense that we document it, since it is one of its main features.

**Comment by twitter-dermot** [comment]
@mikelalcon thanks so much for your prompt response! That's very helpful clarification.

**Comment by sudoforge** [comment]
For context, Copybara is stateless because it relies on the `GitOrigin-RevId` trailer existing in the destination repository in order to determine revision list that needs to be migrated. With this in mind, it isn't _exactly_ stateless; it just isn't keeping state in the same way that most people think about state (e.g. a cache, a database, etc).
