### ISSUE TITLE
Bazel test on current master fails

### ISSUE THREAD

**Issue by massdosage** [google/copybara#198]
Bazel version: `bazel 5.1.1`
Bazel command: ` bazel test //...`
Copybara master git tag: `e2a64dafcbb94dfc6acbac6a03506a04798136e8`
OS: macOS 12.4

I've followed the instructions to set up and install Copybara for the first time from scratch. The build commands all succeed but multiple tests fail. Below is a summary of the issues.

The majority of the tests fail due to being unable to run `hg` with error messages like so:

```
1) testUnknownChanges(com.google.copybara.hg.HgOriginTest)
com.google.copybara.exception.RepoException: Error executing hg: java.io.IOException: Cannot run program "hg" (in directory "/private/var/tmp/_bazel_adrianwoodhead/b517e413cf06325314e824ae409846c9/execroot/com_github_google_copybara/_tmp/8539eeb34b6d835cb3e30ba4bb684426/remote11728139315151007707"): error=2, No such file or directory
```

Then there is this test failure about recursive deletes:

```
1) testRewriteUrl(com.google.copybara.git.GitOriginSubmodulesTest)
com.google.common.io.InsecureRecursiveDeleteException: /private/var/tmp/_bazel_adrianwoodhead/b517e413cf06325314e824ae409846c9/execroot/com_github_google_copybara/_tmp/6e34053742fb177b3f2054f065932a25/testRewriteUrl9101707592707121493/r1/.git: unable to guarantee security of recursive delete
/private/var/tmp/_bazel_adrianwoodhead/b517e413cf06325314e824ae409846c9/execroot/com_github_google_copybara/bazel-out/darwin-fastbuild/testlogs/javatests/com/google/copybara/git/GitOriginSubmodulesTest/test.log
```

Then an error about not being able to run `quilt`:

```
1) parseSkylarkTest(com.google.copybara.transform.patch.QuiltTransformationTest)
java.io.IOException: com.google.copybara.shell.ExecFailedException: java.io.IOException: Cannot run program "/private/var/tmp/_bazel_adrianwoodhead/b517e413cf06325314e824ae409846c9/execroot/com_github_google_copybara/bazel-out/darwin-fastbuild/bin/javatests/com/google/copybara/transform/patch/QuiltTransformationTest.runfiles/com_github_google_copybara/third_party/quilt/quilt" (in directory "/private/var/tmp/_bazel_adrianwoodhead/b517e413cf06325314e824ae409846c9/execroot/com_github_google_copybara/_tmp/60fc0ffa4e9127c0f7175d4172eae532/workdir3961443606400138964"): error=2, No such file or directory
```

Have I missed some pre-requisites? I'm happy to help debug and try out any proposed fixes etc.

**Comment by hsudhof** [comment]
The first one is that you don't have mercurial set up.

The second is odd, but we can add the force flag for that one.

The third is because you don't have quilt installed.

**Comment by massdosage** [comment]
OK, so an option would be to update the documentation to say that installing Mercurial and Quilt are pre-requisites for running the tests? Or alternatively the `assume` functionality in JUnit4 could be used in those tests to check whether those executables are present and if not skip those tests?

**Comment by hsudhof** [comment]
The tests are meant to be run in the environment brought up by cloudbuild.sh; neither mercurial nor quilt are required for running copybara unless these features are actively used. 

I could see pulling quilt into the workspace instead as it's less common.

**Comment by massdosage** [comment]
OK, I could have a go at an MR to run the tests conditionally based on the presence/absence of Mercurial and Quilt, or to update the documentation so as to not expect certain tests to pass if they're not there?

**Comment by hsudhof** [comment]
Yes, that's reasonable.
