### ISSUE TITLE
Update existing copy destination with --force-with-lease?

### ISSUE THREAD

**Issue by smelc** [google/copybara#205]
Thanks for the hard work on copybara :pray: We are using copybara at [kaiko.ai](https://www.kaiko.ai/) and have one feature request (or a link to the existing argument to achieve what we need?):

Is it possible for `copybara` to update an existing branch of the destination repo, when using a copy workflow? In our way of working, we want to update a branch generated by copybara until some condition is met, then merge. Until the merge, we need `copybara` to `git push --force-with-lease` to update the already existing branch.

If doing so right now, it fails as follows:

```
> java -jar /home/churlin/tools/copybara_deploy.jar migrate /tmp/copy.bara.sky default --init-history
Sep 01, 2022 11:04:56 AM com.google.copybara.Main configureLog
INFO: Setting up LogManager
Copybara source mover (Version: Unknown version)
Task: Removing excluded origin files
INFO: Removed 1080 files from workdir that do not match origin_files
Task: Git Destination: Pushing to git@github.com:kaiko-ai/kaiko-eng.git refs/heads/copybara@copy@r3ypNwn3yjCJHv3j
ERROR: Failed to push to git@github.com:kaiko-ai/kaiko-eng.git [HEAD:refs/heads/copybara@copy@r3ypNwn3yjCJHv3j], because local/origin history is behind destination
  CAUSED BY: Error executing 'git --git-dir=/home/churlin/copybara/cache/git_repos/git%40github%2Ecom%3Akaiko-ai%2Fkaiko-eng%2Egit --work-tree=/home/churlin/copybara/temp/git_dest12225703393656663062 push --progress git@github.com:kaiko-ai/kaiko-eng.git HEAD:refs/heads/copybara@copy@r3ypNwn3yjCJHv3j'(exit code 1). Stderr: To github.com:kaiko-ai/kaiko-eng.git
 ! [rejected]        HEAD -> copybara@copy@r3ypNwn3yjCJHv3j (non-fast-forward)
error: failed to push some refs to 'github.com:kaiko-ai/kaiko-eng.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

It seems to me there is `--git-destination-push` for this use case for PR workflows (introduced in [this copybara commit](https://github.com/google/copybara/commit/41891ab1317eb09cad73388ecfd4ae2fc246d52e)) but there is nothing for copy workflows. Am I correct?

If the feature can be added, any pointers to the implementation would be appreciated. We may consider writing it.

---

For the record, we use a simple copy workflow like this one:

```shell
core.workflow(
    name = "default",

    origin = git.origin(
        url = source_url,
        ref = "master",
    ),
    destination = git.destination(
        url = monorepo_url,
        fetch = "main",
        push = "copybara@copy@generated-randomly-first-time-reused-until-merge",
    ),

    origin_files = ...
    destination_files = ...

    authoring = authoring.pass_thru("kaiko-bot <clement@kaiko.ai>"),
    mode = "SQUASH",
)
```

**Comment by mikelalcon** [comment]
Hi!

So if I understand correctly you want to have a branch with a single commit that you overwrite in each migration until it is merged to a `main` branch right?

I don't remember much of the context of 41891ab1317eb09cad73388ecfd4ae2fc246d52e as it happened long time ago :). 

Is there any reason to not reuse the push branch once merged? That should simplify things as you could use : 
```
fetch = "main",
push = "to_be_merged"
```
And run copybara with `--git-destination-non-fast-forward`.

Is this for some sort of review sytems (e.g. Gerrit, GitHub), if so, it might make sense to add support for that review system instead.

**Comment by mikelalcon** [comment]
Cool, let us know how it goes! :)

**Comment by smelc** [comment]
I confirm that `--git-destination-non-fast-forward` allows me to update the copy's workflow destination branch after its initial creation, which is what I needed. Thanks for having pointed it out :pray:

**Comment by mikelalcon** [comment]
Nice! thanks for confirming!
