### ISSUE TITLE
Command 'git' killed by Copybara after timeout (900s)

### ISSUE THREAD

**Issue by Will5** [google/copybara#232]
In one repository, I've started seeing timeout errors. I think the repo may be getting too large, at least for CI. How can I increase the timeout?

```
TASK: Git Destination: Fetching: git@github.com:[REDACTED]/[REDACTED].git refs/heads/main
ERROR: Error executing 'git': Command 'git' killed by Copybara after timeout (900s). If this fails during a fetch use --fetch-timeout flag.
Exit info: Process terminated by signal 15
  CAUSED BY: Command 'git' killed by Copybara after timeout (900s). If this fails during a fetch use --fetch-timeout flag.
```

**Comment by hsudhof** [comment]
Have you  tried the flag suggested in the error message?

**Comment by Will5** [comment]
> Have you tried the flag suggested in the error message?

No, because the message isn't clear to me on how it should be applied. The message mentions the 'git' command was killed, but I am not explicitly calling 'git'. Should it be on the 'copybara' command? I didn't see any mention of it in the documentation.

> I believe --fetch-timeout was deprecated and renamed to repo-timeout some time ago.
> 
> Would recommend rebasing your copy of the project and using --repo-timeout. ctrl-f "--repo-timeout" at https://github.com/google/copybara/blob/master/docs/reference.md

Thanks, you are right! I will give that a try.

- [Alias --fetch-timeout to --repo-timeout](https://github.com/google/copybara/commit/ec33989b924833e65c1e59c6cad861e978bd8af1)
- [Remove --fetch-timeout](https://github.com/google/copybara/commit/48254960fb86b5fb439bf8c7d78a011168d328b2)

**Comment by Will5** [comment]
Thanks, this works
