### ISSUE TITLE
Transforming line endings?

### ISSUE THREAD

**Issue by rpavlik** [google/copybara#237]
I'm trying to troubleshoot why a copybara-driven import of some files from a vendor repo is breaking my CI, and I think it's because Microsoft has `\r\n` in their repo which we don't typically have (and is banned by our gitattributes)  Is there an easy transform for line ending change, or is a transform of `\r\n` to `\n` the easiest?

I'm currently using this, and I think it is working...

```
        core.replace("\r\n", "\n", multiline=True),
```

**Comment by mikelalcon** [comment]
That is probably the most straightforward way.
