### ISSUE TITLE
Why 'user.name' and/or 'user.email' must be configured ?

### ISSUE THREAD

**Issue by AlexTrotsenko** [google/copybara#263]
I run copybara on our CI and faced ['user.name' and/or 'user.email' are not configured](https://github.com/google/copybara/blob/c23479abd19d4091ce84f9c4fe61cb126bb10b3b/java/com/google/copybara/git/GitDestination.java#L162) issue. 

As far as I see, currently the only way to avoid setting `git config --global` is to specify `--git-committer-email` command line option.

Why `authoring = authoring.pass_thru("Copybara <copybara@example.com>"),` in sky file is not enough?

**Comment by mikelalcon** [comment]
The committer is set to the local user. The author is set to the one from
the origin/workflow configuration.

**Comment by AlexTrotsenko** [comment]
@mikelalcon thanks for the quick reply and information provided. Indeed it is absolutely makes sense. 

I am wondered if you think it worth to also add the option to specify git committer in the sky file?
Or is it preferable to have  committer set to the _actual_ CI "technical user" instead of having it set statically to something like `"Copybara <copybara@example.com>"` ?

**Comment by mikelalcon** [comment]
We have `--git-committer-email` and `--git-committer-name` too. I think it is better to not set statically so that if you do a manual export it clearly says that you were the one exporting instead of an automated service, etc.

**Comment by AlexTrotsenko** [comment]
@mikelalcon thanks for the feedback and confirmation 👍

Since it also makes sense for you to keep it static - may I possibly ask you if you are happy to consider having this property in the sky file as well?

**Comment by mikelalcon** [comment]
Sounds good! could you use an authoring object? (Receive string from starlark in the format of "foo <foo@example.com>" and then convert it to `Author` with `Author.parse(String)`

**Comment by AlexTrotsenko** [comment]
> Sounds good! could you use an authoring object? (Receive string from starlark in the format of "foo <[foo@example.com](mailto:foo@example.com)>" and then convert it to `Author` with `Author.parse(String)`

Thanks for the confirmation and your suggestion about re-using Author. I was about to ask if it ok for you as well :)
