### ISSUE TITLE
Calling different sky files from copy.bara.sky

### ISSUE THREAD

**Issue by ov-wagle** [google/copybara#268]
Hello, 

I am currently working on a project where I have to replace various words from the comments. I am using `core.replace()` to do so. However, as the list is quite big, is there a way where I can list the replacement rules in multiple sky files and invoke those files from copy.bara.sky file?

My project has multiple directories. I want to write a sky file per directory and the main sky file will invoke all the child sky files.

**Comment by hsudhof** [comment]
Yes, starlark has a `load`  statement to include other files. You will want to write a function that returns a list of transforms to be added to your transform list.

**Comment by ov-wagle** [comment]
Thanks @hsudhof. Is there an example present somewhere? I am completely new to Copybara and an example would be a great help.

**Comment by jordanlin00** [comment]
```
# copy.bara.sky
load("common", "my_dict", "my_transforms")

core.console.info("this is my dict -" + str(my_dict))

core.workflow(
    ...
    transformations = my_transforms
    ...
)
```

```
# common.bara.sky
my_dict = {
    "capybara": "copybara",
    "original": "replacement"
}

def my_transforms():
    return [
	core.replace(
            before = key,
            after = my_dict[key],
            paths = glob(["**"])
        )
        for key in my_dict
    ]  

```

**Comment by ov-wagle** [comment]
Thank you @hsudhof @jordanlin00 for the help.
