### ISSUE TITLE
No new changes to import for resolved ref: ITERATIVE move

### ISSUE THREAD

**Issue by DarthHater** [google/copybara#27]
Having a bit of an issue getting copybara to move changes for an internal repo. We recreated an external repo and I keep getting this (external repo is empty). I imagine there is a local repo on my laptop that is keeping track of all this and is like "I ALREADY MOVED THIS!" but I don't know what it is to blow it away. Maybe I'm not right though :)

copy.bara.sky:
```
# Update these references to your orginzations repos
sourceUrl = "git@github.com:sonatype/nexus-repository-p2-internal.git"
destinationUrl = "git@github.com:sonatype/nexus-repository-p2.git"

core.workflow(
    name = "default",
    origin = git.origin(
        url = sourceUrl,
        ref = "master",
    ),
    destination = git.destination(
        url = destinationUrl,
        fetch = "master",
        push = "master",
    ),
    mode = "ITERATIVE",
    # Change path to the folder you want to publish publicly
    origin_files = glob(["**"], exclude = ["copy.bara.sky"]),
    destination_files = glob(["**"]),

    authoring = authoring.pass_thru("Me <me@me.com>"),
)
```

```
nexus-repository-p2-internal  master ✅  ~/code/tools/copybara/bazel-bin/java/com/google/copybara/copybara copy.bara.sky --force --last-rev=8b55debc2b4820f5f287dde93afe4be1b969e793
Copybara source mover (Version: Unknown version)
Task: Git Origin: Initializing local repo
WARN: No new changes to import for resolved ref: 8b55debc2b4820f5f287dde93afe4be1b969e793
```

Appreciate any help, as per usual.

**Comment by denian** [comment]
Is 8b55debc2b4820f5f287dde93afe4be1b969e793 the last commit in your private repo? If so, you should use the first one, assuming you want to import everything, or the sha1 previous to that one, if you don't care about all the history.

Currently we don't have good support for importing all the history from Git from scratch, given that there is no "zero" sha1 in Git that you can pass as --last-rev. At some point we want to add a flag like --git-import-all that imports from the very first commit.

A workaround for this for now would be, assuming that you have this history:

```
sha3 - Third commit
sha2 - Second commit
sha1 - First commit
```


To run first (note that I'm not using --last-rev):

`copybara copy.bara.sky sha1 --force`

And, from that moment on, simply run:

`copybara copy.bara.sky`

And Copybara will figure out which is the next change to import.

**Comment by DarthHater** [comment]
Hell yeah, worked. Thanks!
