### ISSUE TITLE
ITERATIVE mode only copies merge commits

### ISSUE THREAD

**Issue by luzhanning** [google/copybara#283]
I'm migrating repos to monorepo for my company. Right now I'm using ITERATIVE mode+ first_parent=true, and it only copies empty merge commits to monorepo. When I set first_parent to false, although it copies all the actual commits, "git log" shows many unrelated commits to a file. Is there anything I can do to make git history consistent with old repos?

**Comment by mikelalcon** [comment]
`include_branch_commit_logs = True` should give you a better message. It is not perfect but at least you get the commit description while using `first_parent = True`
