### ISSUE TITLE
glob for push_exclude not working with negative patterns

### ISSUE THREAD

**Issue by bitofbreeze** [google/copybara#297]
I'm trying to exclude all folders in apps/ except apps/want/ using the pattern `apps/!(want)/**`. However, I still end up with all folders in apps/ in the destination repo. Am I using this incorrectly?

**Comment by mikelalcon** [comment]
Glob support + and -. You can do something like:

`glob(include = ["**"], exclude = ["apps/**"]) + glob(include = ["apps/want/**"])`
