### ISSUE TITLE
Create a docker image with copybara

### ISSUE THREAD

**Issue by wstrange** [google/copybara#39]
It would be super handy to have a docker image that can run copybara. 

Consider adding it to  https://github.com/GoogleCloudPlatform/cloud-builders

**Comment by denian** [comment]
Hi Warren, 

Yes, that's something we had in mind for a while, but we didn't have the bandwidth.  

One good thing is that we have been working on an internal service for a while, and it relies heavily on the tool. IOW, the tool is prepared to work in "service mode".

We'll try to work on this.

Thanks!
