### ISSUE TITLE
Document building copybara uberjar (copybara_deploy.jar)

### ISSUE THREAD

**Issue by jdanekrh** [google/copybara#40]
Most users will probably want to build not with the command in the README.md, but instead use

    bazel build //java/com/google/copybara:copybara_deploy.jar

This produces an uberjar at

    [,,,]
    Target //java/com/google/copybara:copybara_deploy.jar up-to-date:
      bazel-bin/java/com/google/copybara/copybara_deploy.jar
    [....]

I believe this is the typical way how one would want to build copybara. Figuring this out may be needlessly difficult for people unfamiliar with the build system.

**Comment by mikelalcon** [comment]
Yeah, that makes sense.
