### ISSUE TITLE
Include labels in GitHub PR body

### ISSUE THREAD

**Issue by Yannic** [google/copybara#91]
Is there a way to add the labels of a change to the body of the PullRequest created by `git.github_pr_destination`?

If there isn't, I'd be happy to contribute a patch implementing this if that's something you'd want to support.

**Comment by mikelalcon** [comment]
After
https://github.com/google/copybara/commit/9f6077b03c92974dcc5e2106f555d1953d343902
it
should be possible. Have you give it a try?

Cheers,
Mikel.

**Comment by Yannic** [comment]
That's great news! I did see something mentioned in the docs, but it didn't work for me. Let me update my version and give it a try.
