### ISSUE TITLE
copybara: command not found

### ISSUE THREAD

**Issue by dnzguzel** [google/copybara#92]
Hi, I am installing copybara on Centos 7 according to your documentation. But in the end, I am taking "copybara: command not found" error. How can I solve this problem?

**Comment by mikelalcon** [comment]
What part of the documentation are you following?



$ bazel build //java/com/google/copybara

INFO: Analysed target //java/com/google/copybara:copybara (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //java/com/google/copybara:copybara up-to-date:
  bazel-bin/java/com/google/copybara/copybara.jar
  bazel-bin/java/com/google/copybara/copybara
INFO: Elapsed time: 13.698s, Critical Path: 12.11s
INFO: Build completed successfully, 16 total actions

$  bazel-bin/java/com/google/copybara/copybara
Jun 20, 2019 8:51:08 AM com.google.copybara.Main configureLog
INFO: Setting up LogManager
Copybara source mover (Version: Unknown version)
Task: Running migrate
ERROR: Configuration file missing for 'migrate' subcommand.

ERROR: Try 'copybara help'.

**Comment by dnzguzel** [comment]
I am installing according to this URL https://github.com/google/copybara#getting-started-using-copybara

**Comment by mikelalcon** [comment]
Please provide the output of the commands described above. Note that Bazel build doesn't install Copybara in your PATH. See my previous comment about running " bazel-bin/java/com/google/copybara/copybara" once compiled.

**Comment by dnzguzel** [comment]
I don't understand what can I do. My script outputs is like yours.
[root@copybara]# bazel build //java/com/google/copybara
Starting local Bazel server and connecting to it...
INFO: Analyzed target //java/com/google/copybara:copybara (74 packages loaded, 1595 targets configured).                                                      
INFO: Found 1 target...                                                                                                                                       
INFO: Deleting stale sandbox base /root/.cache/bazel/_bazel_root/a765a7fc712e9ceaa1dc55dfa1085dfe/sandbox                                                     
Target //java/com/google/copybara:copybara up-to-date:                                                                                                        
  bazel-bin/java/com/google/copybara/copybara.jar                                                                                                             
  bazel-bin/java/com/google/copybara/copybara                                                                                                                 
INFO: Elapsed time: 11.765s, Critical Path: 0.98s                                                                                                             
INFO: 0 processes.                                                                                                                                            
INFO: Build completed successfully, 2 total actions
[root@copybara]# bazel-bin/java/com/google/copybara/copybara
Jun 27, 2019 2:46:53 PM com.google.copybara.Main configureLog
INFO: Setting up LogManager
Copybara source mover (Version: Unknown version)
Task: Running migrate                                                                                                                                         
ERROR: Configuration file missing for 'migrate' subcommand.

ERROR: Try 'copybara help'.

**Comment by mikelalcon** [comment]
This is is Copybara running:

> [root@copybara]# bazel-bin/java/com/google/copybara/copybara
> Jun 27, 2019 2:46:53 PM com.google.copybara.Main configureLog
> INFO: Setting up LogManager
> Copybara source mover (Version: Unknown version)
> Task: Running migrate
> ERROR: Configuration file missing for 'migrate' subcommand.
> 

You can also build:

` bazel build java/com/google/copybara:copybara_deploy.jar`

and then copy `bazel-bin/java/com/google/copybara/copybara_deploy.jar` to any location and run it like

` java -jar some/location/copybara_deploy.jar`

**Comment by dnzguzel** [comment]
I copied the jar file to any location(under the /root folder) that you said. After that, I run the jar file with java -jar but I am taking following error.
[root@~]# java -jar copybara_deploy.jar                                                                                                            
Jun 27, 2019 4:05:08 PM com.google.copybara.Main configureLog
INFO: Setting up LogManager
Copybara source mover (Version: Unknown version)
Task: Running migrate                                                                                                                                         
ERROR: Configuration file missing for 'migrate' subcommand.
ERROR: Try 'copybara help'.

**Comment by mikelalcon** [comment]
That is Copybara running :). Create a config file (copy.bara.sky) and run
it like

java -jar copybara_deploy.jar path/to/copy.bara.sky

**Comment by dnzguzel** [comment]
This time, I am taking the following error.

```
[root@~]# java -jar copybara_deploy.jar copybara/copy.bara.sky 
Jun 28, 2019 9:11:50 AM com.google.copybara.Main configureLog
INFO: Setting up LogManager
Copybara source mover (Version: Unknown version)
Task: Git Destination: Fetching: file:///tmp/foo refs/heads/master                                                                                            
ERROR: Cannot find last imported revision. Use --force if you really want to proceed with the migration
  CAUSED BY: Previous revision label GitOrigin-RevId could not be found in GitDestination{repoUrl=file:///tmp/foo, fetch=master, push=master} and --last-rev or --init-history flags were not passed
```

**Comment by mikelalcon** [comment]
*Use --force if you really want to proceed with the migration*

I also recommend running with --dry-run until you are confortable with Copybara.

**Comment by dzintars** [comment]
Or make an alias into your `~/.zshrc` (or alternative):
```
alias copybara = 'java -jar ~/code/github.com/google/copybara/bazel-bin/java/com/google/copybara/copybara_deploy.jar'
```

And call it simply by `copybara copy.bara.sky --force`
